### ISSUE TITLE
[Bug] Does it not work with addon smelting recipes?

### ISSUE THREAD

**Issue by WildFyr16** [Hardel-DW/BetterFurnace#2]
Heya!
Our server has another datapack that adds more, custom, food. Some of the items uses a furnace/smoker/campfire to smelt/cook things. A Roasted Carrot for example; however, I am unable to place a carrot in the Extreme Furnace. Is this a limitation of the datapack, something I have to manually add to the datapack, or can it just not be done at all?
![Medal_uIBPtnVy2V](https://github.com/user-attachments/assets/2d19c161-c6fc-465b-81c2-46ac83a4464c)
![Medal_MHDIDfbP5P](https://github.com/user-attachments/assets/dffa4a5f-8307-4b0a-96d6-274a057d0ba9)

**Comment by Hardel-DW** [comment]
The datapack does not modify recipes. I'm only modifying the cooking speed, try to see if the problem comes from the other datapacks.
The 7 new furnaces are classic furnaces with an applied texture. 
If it doesn't work only with the extreme, I've done something wrong.

**Comment by Hardel-DW** [comment]
I think that the pack you added only added the cooking of the carrots in the Smoker.

**Comment by WildFyr16** [comment]
Huh, I could have sworn I tried it in a furnace before... guess not. Yep it only added it to the Smoker and the Campfire
